/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.patient;
import model.patientList;
import model.person;
import model.personList;

/**
 *
 * @author mengxiazhang
 */
public class SearchJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchJPanel
     */
    
    personList list;
    patientList list2;
    
    public SearchJPanel(personList list, patientList list2) {
        initComponents();
        
        this.list = list;
        this.list2 = list2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearch = new javax.swing.JTable();
        btnSearchEv = new javax.swing.JButton();
        btnSearchPatient = new javax.swing.JButton();
        btnDeleteEv = new javax.swing.JButton();
        btnDeletePatient = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search Panel");

        tblSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Gender", "City", "Community", "House", "Blood pressure"
            }
        ));
        jScrollPane1.setViewportView(tblSearch);

        btnSearchEv.setText("Search person");
        btnSearchEv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchEvActionPerformed(evt);
            }
        });

        btnSearchPatient.setText("Search patient");
        btnSearchPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPatientActionPerformed(evt);
            }
        });

        btnDeleteEv.setText("Delete person");
        btnDeleteEv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEvActionPerformed(evt);
            }
        });

        btnDeletePatient.setText("Delete patient");
        btnDeletePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePatientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSearchPatient)
                        .addGap(44, 44, 44)
                        .addComponent(btnDeletePatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSearchEv)
                        .addGap(44, 44, 44)
                        .addComponent(btnDeleteEv, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(401, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSearchEv, btnSearchPatient});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchEv)
                    .addComponent(btnDeleteEv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchPatient)
                    .addComponent(btnDeletePatient))
                .addContainerGap(169, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchEvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchEvActionPerformed
        // TODO add your handling code here:
        
        populateTable();
        JOptionPane.showMessageDialog(null, "Search succeed.");
        
    }//GEN-LAST:event_btnSearchEvActionPerformed

    private void btnSearchPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPatientActionPerformed
        // TODO add your handling code here:
        populateTable2();
        JOptionPane.showMessageDialog(null, "Search succeed.");
    }//GEN-LAST:event_btnSearchPatientActionPerformed

    private void btnDeleteEvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEvActionPerformed
        // TODO add your handling code here:
        int selectRowIndex = tblSearch.getSelectedRow();
        
        if (selectRowIndex<0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblSearch.getModel();
        person selectedPerson = (person) model.getValueAt(selectRowIndex, 0);
        
        list.deletePerson(selectedPerson);
        
        JOptionPane.showMessageDialog(this, "Person information is deleted");
        
        populateTable();
    }//GEN-LAST:event_btnDeleteEvActionPerformed

    private void btnDeletePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePatientActionPerformed
        // TODO add your handling code here:
        int selectRowIndex = tblSearch.getSelectedRow();
        
        if (selectRowIndex<0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblSearch.getModel();
        patient selectedPatient = (patient) model.getValueAt(selectRowIndex, 0);
        
        list2.deletePatient(selectedPatient);
        
        JOptionPane.showMessageDialog(this, "Patient information is deleted");
        
        populateTable2();
    }//GEN-LAST:event_btnDeletePatientActionPerformed

    private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblSearch.getModel();
        model.setRowCount(0);
        
               
        for (person p : list.getPerson()){
                Object[] row = new Object[9];
                
                row[0] = p;
                row[1] = p.getAge();
                row[2] = p.getGender();
                row[3] = p.getCity();
                row[4] = p.getCommunity();
                row[5] = p.getHouse();
                row[6] = p.getBloodPressure();
                model.addRow(row);
            } 
    }
    
    private void populateTable2() {
        
        DefaultTableModel model = (DefaultTableModel) tblSearch.getModel();
        model.setRowCount(0);
        
               
        for (patient p : list2.getPatient()){
                Object[] row = new Object[9];
                
                row[0] = p;
                row[1] = p.getAge();
                row[2] = p.getGender();
                row[3] = p.getCity();
                row[4] = p.getCommunity();
                row[5] = p.getHouse();
                row[6] = p.getBloodPressure();
                model.addRow(row);
            } 
    }
        
        
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteEv;
    private javax.swing.JButton btnDeletePatient;
    private javax.swing.JButton btnSearchEv;
    private javax.swing.JButton btnSearchPatient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSearch;
    // End of variables declaration//GEN-END:variables
}
